### ISSUE TITLE
United States at the top of Country List on Contact Form Page

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#457] opened 2023-06-12 22:08 UTC
https://teamraft.com/contact/ 

The Contact Us form the Country selector is in alphabetical, let's have US be brought to the top and then have it go alphabetical below.

**Comment by benmarte** [comment] 2023-06-15 13:04
Closing since this is a duplicate of #442

**Closed by benmarte** 2023-06-15 13:04 UTC
Labels: enhancement, Ready
